name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      # ✅ Debug Step: List workspace contents
      - name: Debug - List workspace contents
        run: ls -R /github/workspace

      # ✅ Debug Step: Print environment variables
      - name: Debug - Print environment variables
        run: env

      # ✅ Debug Step: Print API Token (masked in logs)
      - name: Debug - Print API Token
        run: echo "Token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}"


      # ✅ Debug Step: List workspace contents
      - name: Debug - List workspace contents
        run: ls -R /github/workspace

      # ✅ Debug Step: Print environment variables
      - name: Debug - Print environment variables
        run: env

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install API Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt

      # ✅ Debug Step: Print API Token (masked in logs)
      - name: Debug - Print API Token
        run: echo "Token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}"

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/static"
          api_location: "/api"
          output_location: "/"
          api_build_command: "python -m pip install --upgrade pip && pip install -r api/requirements.txt"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
